# Generated by Django 6.0 on 2025-12-27 00:25

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_profil_poste'),
        ('broyage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('06H-14H', '06H-14H'), ('14H-22H', '14H-22H'), ('22H-06H', '22H-06H'), ('06H-18H', '06H-18H'), ('18H-06H', '18H-06H')], default='06H-14H', max_length=10)),
                ('start_post', models.TimeField()),
                ('end_post', models.TimeField()),
                ('duree_post', models.DurationField(default=datetime.timedelta(0))),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
                'ordering': ['post'],
            },
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('livraison', models.IntegerField(blank=True, default=0, null=True)),
                ('casse', models.IntegerField(blank=True, default=0, null=True)),
                ('vrack', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('date', models.DateField(default=datetime.datetime(2025, 12, 27, 0, 24, 59, 923340, tzinfo=datetime.timezone.utc))),
                ('created', models.DateField(default=datetime.datetime(2025, 12, 27, 0, 24, 59, 923356, tzinfo=datetime.timezone.utc))),
                ('slug', models.SlugField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.post')),
            ],
            options={
                'verbose_name': 'Packing',
                'verbose_name_plural': 'Packing',
                'ordering': ('-date', 'post'),
            },
        ),
        migrations.CreateModel(
            name='Pannes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('MEC', 'MECANIQUE'), ('ELECT', 'ELECTRIQUE'), ('AUTO', 'AUTOMATISME'), ('LAB', 'LABORATOIRE'), ('PROD', 'PRODUCTION'), ('ARRET PROG', 'ARRET PROGRAMME'), ('CEET', 'CEET'), ('COMM', 'COMMERCIALE')], default='MEC', max_length=50)),
                ('section', models.CharField(blank=True, choices=[('broyage', 'broyage'), ('packing', 'packing')], max_length=50, null=True)),
                ('start_panne', models.TimeField()),
                ('end_panne', models.TimeField()),
                ('duree', models.DurationField()),
                ('description', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
                ('broyage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broyage.broyage')),
                ('packing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packing.packing')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site')),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Panne',
                'ordering': ['-date'],
            },
        ),
    ]
