# Generated by Django 6.0 on 2025-12-27 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packing',
            name='created',
            field=models.DateField(default=datetime.datetime(2025, 12, 27, 0, 26, 29, 709651, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 27, 0, 26, 29, 709633, tzinfo=datetime.timezone.utc)),
        ),
    ]
