# Generated by Django 6.0 on 2025-12-27 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_alter_packing_created_alter_packing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packing',
            name='created',
        ),
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 27, 0, 40, 20, 882301, tzinfo=datetime.timezone.utc)),
        ),
    ]
