# Generated by Django 6.0.1 on 2026-01-12 21:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0003_remove_broyage_post_remove_broyage_site_and_more'),
        ('packing', '0003_remove_packing_created_alter_packing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pannes',
            options={'ordering': ['-packing__date'], 'verbose_name': 'Panne', 'verbose_name_plural': 'Panne'},
        ),
        migrations.RemoveField(
            model_name='pannes',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pannes',
            name='section',
        ),
        migrations.RemoveField(
            model_name='pannes',
            name='site',
        ),
        migrations.AlterField(
            model_name='packing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pannes',
            name='broyage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broyage.totaliseur_1'),
        ),
    ]
