# Generated by Django 6.0.1 on 2026-01-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_alter_pannes_options_remove_pannes_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pannes',
            options={'verbose_name': 'Panne', 'verbose_name_plural': 'Panne'},
        ),
    ]
