# Generated by Django 6.0 on 2026-01-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0005_production'),
        ('packing', '0005_alter_pannes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pannes',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='broyage.production'),
        ),
    ]
