# Generated by Django 6.0 on 2026-01-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0006_pannes_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='packing',
            name='consignes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
