# Generated by Django 5.2.7 on 2025-11-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('opérateur', 'Opérateur')], default='Opérateur', max_length=50),
        ),
    ]
