# Generated by Django 5.2.7 on 2025-11-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profil_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('broyage', 'Opérateur Broyage'), ('packing', 'Responsable Packing'), ('maintenance', 'Technicien Maintenance'), ('administration', 'Administration'), ('laborantin', 'Laborantin'), ('broyage', 'Responsable Broyage')], max_length=100),
        ),
    ]
