# Generated by Django 5.2.7 on 2025-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profil_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('broyage', 'Opérateur Broyage'), ('packing', 'Responsable Packing'), ('maintenance', 'Technicien Maintenance'), ('administration', 'Administration'), ('laborantin', 'Laborantin')], max_length=100),
        ),
    ]
