# Generated by Django 6.0.1 on 2026-01-12 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profil_poste'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='section',
            field=models.CharField(blank=True, choices=[('broyage', 'Broyage'), ('packing', 'Packing'), ('maintenance', 'Maintenance'), ('laboratoire', 'Laboratoire'), ('administration', 'Administration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('operateurBroyage', 'Opérateur Broyage'), ('responsablPacking', 'Responsable Packing'), ('maintenance', 'Technicien Maintenance'), ('administration', 'Administration'), ('laborantin', 'Laborantin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
    ]
