# Generated by Django 6.0 on 2026-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profil_section_alter_profil_poste_alter_profil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('chefProduction', 'Chef Production'), ('operateurBroyage', 'Opérateur Broyage'), ('responsablPacking', 'Responsable Packing'), ('maintenance', 'Technicien Maintenance'), ('administration', 'Administration'), ('laborantin', 'Laborantin')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='section',
            field=models.CharField(blank=True, choices=[('production', 'Production'), ('broyage', 'Broyage'), ('packing', 'Packing'), ('maintenance', 'Maintenance'), ('laboratoire', 'Laboratoire'), ('administration', 'Administration')], max_length=50, null=True),
        ),
    ]
