# Generated by Django 6.0 on 2026-01-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profil_poste_alter_profil_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('chefQuart', 'Chef de Quart'), ('chefProduction', 'Chef Production'), ('operateurBroyage', 'Opérateur Broyage'), ('responsablPacking', 'Responsable Packing'), ('maintenance', 'Technicien Maintenance'), ('administration', 'Administration'), ('laborantin', 'Laborantin')], max_length=100),
        ),
    ]
