# Generated by Django 6.0 on 2025-12-27 00:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('compt_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('clinker_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gypse_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dolomite_fin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dif_compt', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dif_clinker', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dif_dolomite', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('dif_gypse', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Grinding',
                'verbose_name_plural': 'Grinding',
                'ordering': ['site', '-date', 'post'],
            },
        ),
        migrations.CreateModel(
            name='Totaliseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('clinker_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('gypse_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('dolomite_debut', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Totaliseur',
                'verbose_name_plural': 'Totaliseur',
                'ordering': ('-date', 'post__post'),
            },
        ),
    ]
