# Generated by Django 6.0 on 2025-12-27 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_profil_poste'),
        ('broyage', '0001_initial'),
        ('packing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broyage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.post'),
        ),
        migrations.AddField(
            model_name='broyage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site'),
        ),
        migrations.AddField(
            model_name='broyage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='totaliseur',
            name='post',
            field=models.ForeignKey(default='06H-14H', on_delete=django.db.models.deletion.CASCADE, to='packing.post'),
        ),
        migrations.AddField(
            model_name='totaliseur',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site'),
        ),
        migrations.AddField(
            model_name='broyage',
            name='totaliseur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='broyage.totaliseur'),
        ),
    ]
