# Generated by Django 6.0.1 on 2026-01-12 21:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profil_poste'),
        ('broyage', '0002_initial'),
        ('packing', '0003_remove_packing_created_alter_packing_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broyage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='broyage',
            name='site',
        ),
        migrations.RemoveField(
            model_name='broyage',
            name='totaliseur',
        ),
        migrations.RemoveField(
            model_name='broyage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='totaliseur',
            name='post',
        ),
        migrations.RemoveField(
            model_name='totaliseur',
            name='site',
        ),
        migrations.CreateModel(
            name='Totaliseur_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('compt_totaliseur_1', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('clinker_totaliseur_1', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('gypse_totaliseur_1', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('dolomite_totaliseur_1', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Totaliseur 1',
                'verbose_name_plural': 'Totaliseur 1',
                'ordering': ('-date', 'post__post'),
            },
        ),
        migrations.CreateModel(
            name='Totaliseur_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compt_totaliseur_2', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('clinker_totaliseur_2', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('gypse_totaliseur_2', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('dolomite_totaliseur_2', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('silo_1', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('silo_2', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('dif_compt', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('dif_clinker', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('dif_gypse', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('dif_dolomite', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=20)),
                ('slug', models.SlugField(default='')),
                ('totaliseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='broyage.totaliseur_1')),
            ],
            options={
                'verbose_name': 'Totaliseur 2',
                'verbose_name_plural': 'Totaliseur 2',
                'ordering': ('-totaliseur__date', 'totaliseur__post__post'),
            },
        ),
    ]
