# Generated by Django 6.0.1 on 2026-01-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0003_remove_broyage_post_remove_broyage_site_and_more'),
        ('packing', '0004_alter_pannes_options_remove_pannes_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broyage',
        ),
        migrations.DeleteModel(
            name='Totaliseur',
        ),
    ]
