# Generated by Django 6.0 on 2026-01-16 16:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profil_poste_alter_profil_section'),
        ('broyage', '0004_delete_broyage_delete_totaliseur'),
        ('packing', '0005_alter_pannes_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('production', models.IntegerField(default=0)),
                ('rendement', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('consignes', models.TextField(blank=True, default='')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('slug', models.SlugField(default='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packing.post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de Production',
                'verbose_name_plural': 'Rapports de Production',
                'ordering': ('-id',),
            },
        ),
    ]
