# Generated by Django 6.0 on 2026-01-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0005_production'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='rendement',
            new_name='conso',
        ),
    ]
