# Generated by Django 6.0 on 2026-01-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0006_rename_rendement_production_conso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaliseur_2',
            name='silo_1',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='totaliseur_2',
            name='silo_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True),
        ),
    ]
