# Generated by Django 6.0 on 2026-01-17 11:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0007_alter_totaliseur_2_silo_1_alter_totaliseur_2_silo_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaliseur_2',
            name='silo_1',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='totaliseur_2',
            name='silo_2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
    ]
