# Generated by Django 6.0 on 2026-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broyage', '0008_alter_totaliseur_2_silo_1_alter_totaliseur_2_silo_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaliseur_2',
            name='silo_1',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='totaliseur_2',
            name='silo_2',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=20),
        ),
    ]
